### ISSUE TITLE
Original problem statement

### ISSUE THREAD

**Issue by bsstokes** [bsstokes/BsPix#1]
The Instagram API provides access to all of the aspects of Instagram. In this project you will write an Android application which uses the Instagram API to provide a user interface for simple interactions with Instagram. Feel free to use almost any framework or library you wish to accomplish this task. We request that you don't use any libraries built specifically to interact with Instagram. We would like to see what you come up with on your own.

Your application should have a minimum version of API level 16, target whatever API level you are comfortable with, and consist of the following views/features:

Login
- [x] Persist OAuth information so user doesn't need to login each time they open the app (#3)
- [x] You are free to use implicit authentication

My User
- [x] Show basic information about the logged in user (name, bio, website, counts) (#4)
- [x] Show image media of the logged in user (#5)
- [x] Show images the logged in user has liked (#6)

Following
- [x] Show users that the logged in user is following (#8)
- [x] For each followed user, show that user's image media (#9)

Image Media
- [x] Large view of image (#7)
- [x] Meta information about the image (caption, location, user, tags) (#7)
- [x] Ability to like / unlike the photo (#10)

To achieve the above features, it may be necessary to create an account for yourself and upload some images for that user using Instagram's official app or through some other means. You will also need to multiple users to the Instagram API sandbox for your project. The sandbox is used for apps that are still in development because Instagram won't let you see any content from non-sandbox users on non-production apps. Leverage these users added to your sandbox for the "Following" portion of the app. You are not required to be able to create an account, submit media, or view video media with this project.

The app definitely does not need to win any design awards, but there should be some effort towards a good user experience. You are more than welcome to rip off designs of other similar content-style apps. Also, make sure that your app functions just as great on a tablet as it does on a phone.

When you're finished, please put your project in a repository on either Github or Bitbucket and send us a link. We'll then do a pair programming session where we'll have some questions for you about your code and possibly make some additions to it.

**Comment by bsstokes** [comment]
Released as [v1.0.0](https://github.com/bsstokes/BsPix/releases/tag/v1.0.0).
